package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"strconv"
	"time"

	"gondos/graph/model"
	"gondos/internal/app"
)

// CreateList is the resolver for the createList field.
func (r *mutationResolver) CreateList(ctx context.Context, list model.ListInput) (*string, error) {
	desc := ""
	if list.Description != nil {
		desc = *list.Description
	}
	input, err := app.NewList(list.Title, desc)
	if err != nil {
		return nil, err
	}

	if err := r.App.UserCreateList(ctx, input); err != nil {
		return nil, err
	}
	return nil, nil
}

// AddItemToList is the resolver for the addItemToList field.
func (r *mutationResolver) AddItemToList(ctx context.Context, listID string, item model.ListItemInput) (*string, error) {
	listIDInt, err := strconv.Atoi(listID)
	if err != nil {
		return nil, err
	}
	input, err := app.NewListItem(int64(listIDInt), item.Body)
	if err != nil {
		return nil, err
	}

	if err := r.App.UserAddItemToList(ctx, input); err != nil {
		return nil, err
	}
	return nil, nil
}

// Lists is the resolver for the lists field.
func (r *queryResolver) Lists(ctx context.Context) ([]*model.List, error) {
	lists, err := r.App.UserLists(ctx)
	if err != nil {
		return nil, err
	}

	modelLists := make([]*model.List, 0)
	for _, v := range lists {
		modelLists = append(modelLists, &model.List{
			ID:          strconv.Itoa(int(v.ID())),
			Title:       v.Title(),
			Description: ptr(v.Description()),
			CreatedAt:   v.CreatedAt().Format(time.RFC3339Nano),
			UpdatedAt:   v.UpdatedAt().Format(time.RFC3339Nano),
		})
	}

	return modelLists, nil
}

// ListItems is the resolver for the listItems field.
func (r *queryResolver) ListItems(ctx context.Context, listID string) ([]*model.ListItem, error) {
	listIDInt, err := strconv.Atoi(listID)
	if err != nil {
		return nil, err
	}

	items, err := r.App.UserListItems(ctx, int64(listIDInt))
	if err != nil {
		return nil, err
	}

	modelListItems := make([]*model.ListItem, 0)
	for _, v := range items {
		modelListItems = append(modelListItems, &model.ListItem{
			ID:        strconv.Itoa(int(v.ID())),
			Body:      v.Body(),
			CreatedAt: v.CreatedAt().Format(time.RFC3339Nano),
			UpdatedAt: v.CreatedAt().Format(time.RFC3339Nano),
		})
	}

	return modelListItems, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
