openapi: 3.0.0
info:
  title: Lister
  description: Save your list
  version: "0.1"
servers: 
  - url: "/" 
paths: 
  /auth/register:
    post: 
      summary: Register a new account
      operationId: authRegister
      requestBody: 
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterRequest"
      responses: 
        '200':
          description: OK
          content: 
            application/xml:
              schema: 
                $ref: "#/components/schemas/AuthRegisterResponse"
        default: 
          $ref: "#/components/responses/default"
              
security: []
components: 
  responses: 
    default:
      description: "error"
      content: 
        application/json:
          schema: 
            $ref: "#/components/schemas/Error"

  schemas: 
    Error:
      required: [code, message]
      properties: 
        code:
          type: string
        message:
          type: string
    AuthRegisterRequest:
      $ref: components/schemas/auth-register-request.yml
    AuthRegisterResponse:
      $ref: components/schemas/auth-register-response.yml
    