openapi: 3.0.0
info:
  title: Lister
  description: Save your list
  version: "0.1"
servers: 
  - url: "/" 
paths: 
  /auth/register:
    post: 
      summary: Register a new account
      operationId: authRegister
      requestBody: 
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterRequest"
      responses: 
        '200':
          description: OK
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/AuthRegisterResponse"
        '422':
          description: validation error
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/ValidationError"
        '4xx':
          description: error
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"

  /auth/login:
    post: 
      summary: Login
      description: Returns JWT token on success
      operationId: authLogin
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/AuthLoginRequest"
      responses: 
        '200':
          description: OK
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/AuthLoginResponse"
        '422':
          description: validation error
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/ValidationError"
        '4xx':
          description: error
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"

security: []
components: 
  schemas: 
    Error:
      required: [code, message]
      properties: 
        code:
          type: string
        message:
          type: string
    ValidationError:
      required: [code, message, params]
      properties: 
        code:
          type: string
        message:
          type: string 
        params:
          type: array
          items: 
            $ref: "#/components/schemas/ValidationErrorParams"
    ValidationErrorParams:
      type: object
        
    AuthRegisterRequest:
      $ref: components/schemas/auth-register-request.yml
    AuthRegisterResponse:
      $ref: components/schemas/auth-register-response.yml
    AuthLoginRequest:
      $ref: components/schemas/auth-login-request.yml
    AuthLoginResponse:
      $ref: components/schemas/auth-login-response.yml