// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"time"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	AccessToken string `json:"access_token"`
}

// AuthRegisterRequest defines model for AuthRegisterRequest.
type AuthRegisterRequest struct {
	Email           string `json:"email"`
	Name            string `json:"name"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"password_confirm"`
}

// AuthRegisterResponse defines model for AuthRegisterResponse.
type AuthRegisterResponse struct {
	CreatedAt string  `json:"created_at"`
	Email     string  `json:"email"`
	Id        float32 `json:"id"`
	Name      string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ListCreateRequest defines model for ListCreateRequest.
type ListCreateRequest struct {
	Description string `json:"description"`
	Title       string `json:"title"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Params  []ValidationErrorParams `json:"params"`
}

// ValidationErrorParams defines model for ValidationErrorParams.
type ValidationErrorParams = map[string]interface{}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = AuthLoginRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = AuthRegisterRequest

// PostUserListsJSONRequestBody defines body for PostUserLists for application/json ContentType.
type PostUserListsJSONRequestBody = ListCreateRequest
